services:
  - type: web
    name: puckstats-api
    env: docker
    dockerfilePath: backend/Dockerfile
    region: oregon
    plan: free
    healthCheckPath: /health
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: ConnectionStrings__DefaultConnection
        value: "postgresql://postgres.gxwdigzfxzbgjzkdzoys:PuckStats2024%21@aws-0-us-east-1.pooler.supabase.com:5432/postgres?sslmode=require"
      - key: ReplayStoragePath
        value: /data/replays
